# Generated by Django 3.0.8 on 2020-08-20 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_watchlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='current_bid',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
