# Generated by Django 3.0.8 on 2020-08-23 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_auto_20200823_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image_url',
            field=models.CharField(blank=True, default='static/auctions/no_image_logo.svg.webp', max_length=1024),
        ),
    ]
