# Generated by Django 3.0.8 on 2020-08-26 07:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_auto_20200825_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='closedproduct',
            name='winning_user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='winning_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
